FROM gcc:latest
WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    libasound2-dev \
    libx11-dev \
    libxrandr-dev \
    libxi-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libxcursor-dev \
    libxinerama-dev \
    mesa-utils \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 https://github.com/raysan5/raylib.git /app/raylib

COPY . .

RUN make oblivion

CMD ["./oblivion"]
